export const MODELS = {
  // FREE
  "llama-3-8b": {
    id: "meta-llama/llama-3-8b-instruct:free",
    name: "Llama 3 8B",
    tier: "free",
    color: "#7c6af7",
  },
  "llama-3.1-8b": {
    id: "meta-llama/llama-3.1-8b-instruct:free",
    name: "Llama 3.1 8B",
    tier: "free",
    color: "#9c8af7",
  },
  "gemma-2-9b": {
    id: "google/gemma-2-9b-it:free",
    name: "Gemma 2 9B",
    tier: "free",
    color: "#f59e0b",
  },
  "gemma-3-12b": {
    id: "google/gemma-3-12b-it:free",
    name: "Gemma 3 12B",
    tier: "free",
    color: "#fbbf24",
  },
  "mistral-7b": {
    id: "mistralai/mistral-7b-instruct:free",
    name: "Mistral 7B",
    tier: "free",
    color: "#ec4899",
  },
  "deepseek-r1": {
    id: "deepseek/deepseek-r1:free",
    name: "DeepSeek R1",
    tier: "free",
    color: "#06b6d4",
  },
  "deepseek-r1-zero": {
    id: "deepseek/deepseek-r1-zero:free",
    name: "DeepSeek R1 Zero",
    tier: "free",
    color: "#0891b2",
  },
  "deepseek-v3": {
    id: "deepseek/deepseek-chat-v3.1",
    name: "DeepSeek V3.1",
    tier: "free",
    color: "#0e7490",
  },
  "phi-3-mini": {
    id: "microsoft/phi-3-mini-128k-instruct:free",
    name: "Phi-3 Mini",
    tier: "free",
    color: "#84cc16",
  },
  "phi-3-medium": {
    id: "microsoft/phi-3-medium-128k-instruct:free",
    name: "Phi-3 Medium",
    tier: "free",
    color: "#65a30d",
  },
  "qwen-2.5-7b": {
    id: "qwen/qwen-2.5-7b-instruct:free",
    name: "Qwen 2.5 7B",
    tier: "free",
    color: "#f97316",
  },
  "qwen-2.5-coder": {
    id: "qwen/qwen-2.5-coder-32b-instruct:free",
    name: "Qwen 2.5 Coder 32B",
    tier: "free",
    color: "#ea580c",
  },
  "llama-3.2-11b": {
    id: "meta-llama/llama-3.2-11b-vision-instruct:free",
    name: "Llama 3.2 11B Vision",
    tier: "free",
    color: "#a78bfa",
  },
  mythomax: {
    id: "gryphe/mythomax-l2-13b:free",
    name: "MythoMax 13B",
    tier: "free",
    color: "#e879f9",
  },
  // LIMITED
  "llama-3-70b": {
    id: "meta-llama/llama-3-70b-instruct",
    name: "Llama 3 70B",
    tier: "limited",
    color: "#10d9a0",
  },
  "llama-3.1-70b": {
    id: "meta-llama/llama-3.1-70b-instruct",
    name: "Llama 3.1 70B",
    tier: "limited",
    color: "#34d399",
  },
  "llama-3.1-405b": {
    id: "meta-llama/llama-3.1-405b-instruct",
    name: "Llama 3.1 405B",
    tier: "limited",
    color: "#6ee7b7",
  },
  "claude-3-haiku": {
    id: "anthropic/claude-3-haiku",
    name: "Claude 3 Haiku",
    tier: "limited",
    color: "#f472b6",
  },
  "gpt-4o-mini": {
    id: "openai/gpt-4o-mini",
    name: "GPT-4o Mini",
    tier: "limited",
    color: "#60a5fa",
  },
  "gpt-4o": {
    id: "openai/gpt-4o",
    name: "GPT-4o",
    tier: "limited",
    color: "#3b82f6",
  },
  "gpt-4.1": {
    id: "openai/gpt-4.1",
    name: "GPT-4.1",
    tier: "limited",
    color: "#2563eb",
  },
  "gpt-5": {
    id: "openai/gpt-5",
    name: "GPT-5",
    tier: "limited",
    color: "#1d4ed8",
  },
  "gemini-flash": {
    id: "google/gemini-flash-1.5",
    name: "Gemini 1.5 Flash",
    tier: "limited",
    color: "#facc15",
  },
  "gemini-pro": {
    id: "google/gemini-pro-1.5",
    name: "Gemini 1.5 Pro",
    tier: "limited",
    color: "#f59e0b",
  },
  "deepseek-r1-nitro": {
    id: "deepseek/deepseek-r1",
    name: "DeepSeek R1 (Full)",
    tier: "limited",
    color: "#22d3ee",
  },
  "mistral-large": {
    id: "mistralai/mistral-large",
    name: "Mistral Large",
    tier: "limited",
    color: "#f43f5e",
  },
};
